### ISSUE TITLE
user-defined waterbodies

### ISSUE THREAD

**Issue by nareshpai** [puruckertom/ubertool_ecorest#1]
Can the Agdrift source code be used for user-defined water bodies?

**Comment by puruckertom** [comment]
The agdrift application here is just the screening part and not the Fortran code:
http://qed.epa.gov/ubertool/agdrift/description
Send me an email at purucker.tom@epa.gov for the login password (if you do not have it)-- because this site is still in beta. You can modify distance to water body but that is it currently.
Best,
Tom

**Comment by nareshpai** [comment]
Thanks! I'll send a message to your e-mail.
